feat: hot potato netinfo so that it can be consumed by those who need it
CompanyCam/companycam-vibe-check pull request #11
Opened 2023-12-08 19:00 UTC by aisflat439

We need to expose NetInfo completely for the initial use at CompayCam. Long term we don't want to expose all of NetInfo. So it's not documented. 

Additionally, we don't expose the `getNonConnectivityInfo` but we do document that it's a private/unstable function. 

This also updates the readme

2023-12-08 19:08 UTC, stevenmcmanus-cocam approved these changes
👍 

Thank you for correcting the copypasta errors in the README, and removing the cpuinfo junk.

2023-12-08 19:59 UTC, jasongaare commented
can you explain how this helps us in the future? like what is the advantage of importing a library from another library? particularly when it's listed as a peer dependency anyway (meaning I have to install it in my main app only to import it here?)

2023-12-08 20:50 UTC, aisflat439 commented
> can you explain how this helps us in the future? like what is the advantage of importing a library from another library? particularly when it's listed as a peer dependency anyway (meaning I have to install it in my main app only to import it here?)

The expectation is that we can write our own version that suits our needs and will be part of the library. In the meantime, since that's not done, passing it through means we have just the one dependency. So it's kinda the point you make, it's already the same as a peer dependency, but because we know what the future holds, it seems worth doing.

2023-12-11 15:40 UTC, jasongaare commented
I'm just not convinced. If we want to write our own version we just should do that when the time comes, and skip this for now; either way we will need to refactor its usages in the future. 

Meaning, ideally we wouldn't call our own version NetInfo but something entirely different, as to prevent confusion. 

I'd recommend either:
(a) not doing the hot potato import for now (am I using that phrase correctly?)
(b) creating a simple wrapper to implement what you are thinking like 

```jsx
import { Connectivity } from `@companycam/vibe-check`

Connectivity.configure({})
Connectivity.fetch({})
```

that more clearly demonstrates we are intending to create our own implementation in the future, but obfuscates (in a way) the current implementation simply forwards the functions to NetInfo

2023-12-11 18:03 UTC, aisflat439 commented
> ple wrapper to implement what you are thinking like

Sure! I think a thin wrapper like you suggest makes a lot of sense. We can do that no problem!

2023-12-12 21:52 UTC, aisflat439 commented
> I'm just not convinced...

We're pulling this out of this PR for now. But we'll work on it as a 🍰 project after we get the key final bits of the logging updates complete!

2023-12-12 23:28 UTC, tdmaienschein requested changes
Just some small suggestions--main request is not setting `console.warn` during the async call

2023-12-12 23:28 UTC, tdmaienschein commented on ios/CompanycamVibeCheck.swift
> +  func parseThermalState(thermalState: ProcessInfo.ThermalState) -> Void {
I think I would rename this to something like `handleThermalState`, to (1) suggest there is a side effect (changing `self.currentThermalState`) (2) avoid the term "parse" since there isn't *really* any parsing happening

2023-12-12 23:28 UTC, tdmaienschein commented on src/index.tsx
> + * intentionally undocumented and should not be used outside of CompanyCam.
Why does CompanyCam need "special" usage privileges that other users of the library shouldn't get?

2023-12-12 23:28 UTC, tdmaienschein commented on src/index.tsx
> +  console.warn = () => {};
I don't think we should do this.  

This could block `console.warn` occurrences outside of just `Device.getPowerState`, plus there is no guarantee how long that will take or whether it will ever complete.  What if it throws?

2023-12-12 23:28 UTC, tdmaienschein commented on README.md
> +Gets the device's current hardware information. This function / method is the main entry point for this library. You SHOULDN'T need to use the other exposed functions. We have provided the more detai
Overall this feels somehow overly perscriptive but without any real reason.  If there *is* a reason to not use the other methods, maybe it would be good to explain.  If there is no good reason, why say anything about it?

2023-12-12 23:28 UTC, tdmaienschein commented on README.md
> +Gets the device's current hardware information. This function / method is the main entry point for this library. You SHOULDN'T need to use the other exposed functions. We have provided the more detai
Small suggestions on the wording: (1) probably just "method" instead of "function / method", since that would be consistent with the RN documentation etc.  (2) "detail-focused" rather than "detail focused"

2023-12-13 15:16 UTC, aisflat439 commented on src/index.tsx
> + * intentionally undocumented and should not be used outside of CompanyCam.
It may well not. But since we didn't plan this, rather we realized we needed it after a convo with Gaare the intent here is to allow us to grow into this use case, rather than committing to it forever.

2023-12-13 15:19 UTC, aisflat439 commented on ios/CompanycamVibeCheck.swift
> +  func parseThermalState(thermalState: ProcessInfo.ThermalState) -> Void {
done!

2023-12-13 15:19 UTC, aisflat439 commented on src/index.tsx
> +  console.warn = () => {};
done!

2023-12-13 15:22 UTC, aisflat439 commented on README.md
> +Gets the device's current hardware information. This function / method is the main entry point for this library. You SHOULDN'T need to use the other exposed functions. We have provided the more detai
Done and wordsmith'd to be less prescriptive.

2023-12-13 18:25 UTC, tdmaienschein approved these changes
Looking great! 🎉

2023-12-13 18:39 UTC, merged